name: "Check our best practices"
description: "Check against our team's best practices for pull requests"

inputs:
  token:
    description: "A GitHub token to add a label to the PR"
    required: true
  jira_token:
    description: "A Jira token to create issues"
    required: true
  regex:
    description: "A custom regular expression for PR titles"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Python and depends
      run: |
        sudo apt install python3 python3-requests
        cd ${{ github.action_path }}
        pip install -r requirements.txt
      shell: bash

    - name: Run all PR best practice checks
      if: github.event_name == 'pull_request_target'
      env:
        BODY: ${{ github.event.pull_request.body }}
        TITLE: ${{ github.event.pull_request.title }}
        TOKEN: ${{ inputs.token }}
        REPOSITORY: ${{ github.event.repository.full_name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        python3 "${{ github.action_path }}/pr_best_practices.py" --pr-description "$BODY"
        set +e
        python3 "${{ github.action_path }}/pr_best_practices.py" --pr-title "$TITLE"
        if [ "$?" == 0 ]; then
          python3 "${{ github.action_path }}/pr_best_practices.py" --add-label --token "$TOKEN" --repository "$REPOSITORY" --pr-number "$PR_NUMBER"
        fi
      shell: bash

    - name: Check for PR Comment
      if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        COMMENT_BODY: ${{ github.event.comment.body }}
        PR_TITLE: ${{ github.event.issue.title }}
        PR_BODY: ${{ github.event.issue.body }}
        JIRA_TOKEN: ${{ inputs.jira_token }}
        REPOSITORY: ${{ github.event.repository.full_name }}
        PR_NUMBER: ${{ github.event.issue.number }}
      shell: bash
      run: |
        if [[ "$COMMENT_BODY" =~ ^/jira ]]; then
          echo "Slash command '/jira' detected"

          # Exit if PR title contains a Jira ticket
          echo "Check if the pull request title contains a Jira reference..."
          set +e
          python3 "${{ github.action_path }}/pr_best_practices.py" --pr-title "$PR_TITLE"
          if [ "$?" == 0 ]; then
            exit 0;
          fi
          set -e

          EPIC_KEY=$(echo "$COMMENT_BODY" | sed -n 's/.*\b\([A-Z]\{2,\}-[0-9]\{1,\}\)\b.*/\1/p')
          JIRA_KEY=$(python3 "${{ github.action_path }}/jira_bot.py" --token "$JIRA_TOKEN" --summary "$PR_TITLE" --description "$PR_BODY" --epic-link "$EPIC_KEY")

          # Add a rocket reaction to the comment
          curl -L ${{github.event.comment.url}}/reactions \
            -X POST \
            -d '{"content":"rocket"}' \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: token $GITHUB_TOKEN"

          # Edit the PR title and body with the JIRA key
          # jq -RSa is used to escape the JSON string
          NEW_TITLE=$(echo "$PR_TITLE ($JIRA_KEY)" | jq -Rsa .)
          NEW_BODY=$(echo "$PR_BODY\r\n\r\nJIRA: [$JIRA_KEY](https://issues.redhat.com/browse/$JIRA_KEY)"| jq -Rsa .)
          curl -L ${{github.event.issue.url}} \
            -X PATCH \
            -d '{"title":'"$NEW_TITLE"',"body":'"$NEW_BODY"'}' \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN"

          # Add a comment to the pull request with the newly created Jira issue link
          python3 "${{ github.action_path }}/pr_best_practices.py" --add-comment "Here's the Jira Task I created for you: [$JIRA_KEY](https://issues.redhat.com/browse/$JIRA_KEY)" --token "$TOKEN" --repository "$REPOSITORY" --pr-number "$PR_NUMBER"
        else
          echo "No recognized slash command found."
        fi
