---
name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  # for merge queue
  merge_group:

jobs:
  check-docs:
    name: "📚 Check if generated docs are up to date"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install prerequisites
        run: pip install -r requirements.txt

      - name: Run check-docs
        run: make check-docs
